name: dust_extinction

channels:
    - astropy

dependencies:
    - python>=2.7
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - scipy
#   - pip:
#       - dependency_from_pip
