[build-system]

requires = ["setuptools",
            "setuptools_scm",
            "wheel"]

build-backend = 'setuptools.build_meta'

[project]
# For PEP 621 version must be defined as dynamic. This is now enforced in setuptools_scm >v8.1
dynamic = ["version"]
